version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GetMeMyRootData2025
      MYSQL_DATABASE: myTodo
      MYSQL_USER: usrtodo
      MYSQL_PASSWORD: GetMeMyData2025
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql